name: CLIPittyClip
channels:
  - bioconda
  - conda-forge
  - chaolinzhanglab
dependencies:
  - wget
  - python
  - trim-galore
  - bedtools
  - samtools
  - pandas
  - numpy
  - scipy
  - seaborn
  - matplotlib
  - perl
  - bowtie2
  - ca-certificates
  - openssl
  - perl-threaded
  - perl-yaml
  - perl-bioperl
  - perl-math-cdf
  - bwa
  - htslib
  - certifi
  - ctk
  - star
  - cutadapt
  - fastp
  - seqkit
  - homer
